default: &default
  # adapter: sqlite3 変更
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode # 追加

development:
  <<: *default
  # database: db/development.sqlite3 変更
  database: FE_ED_dev
  host: localhost
  username: postgres
  password: 6956
test:
  <<: *default
  # database: db/test.sqlite3 変更
  database: _test
  host: localhost
  username: postgres
  password: 6956

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
